
#----------------------------
# General Site Settings

title: Victoria's Portfolio
logo:
author: themefisher
description: Updating and Showcasing My Skills
email: hernandezv@smu.edu
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Victoria! :) 


#-------------------------------
# About (Section and Page)

# About Section
blurb: Currently a Masters of Data Science student at SMU
blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/hernandezv15/CaseStudy2DDS"

  - image: "assets/images/portfolio/item-2.png"
    url: "https://github.com/torih1541/House-Prices-Advanced-Regression-Techniques"

  - image: "assets/images/portfolio/item-3.png"
    url: "https://github.com/torih1541/Case-Study-1-DDS"


# Portfolio Page

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/hernandezv15/CaseStudy2DDS"
    
  - image: "assets/images/portfolio/item-2.png"
    url: "https://github.com/torih1541/House-Prices-Advanced-Regression-Techniques"
 
  - image: "assets/images/portfolio/item-3.png"
    url: "https://github.com/torih1541/Case-Study-1-DDS"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: hernandezv@smu.edu
