---
#-------------------------------
# General Site Settings

title: Portfolio
logo:
author: themefisher
description: This is my portfolio to give updates on projects 
email: hernandezv@smu.edu
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Victoria! :) 


#-------------------------------
# About (Section and Page)

# About Section
blurb: Currently a Masters of Data Science student at SMU
blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/hernandezv15/CaseStudy2DDS"

  - image: "assets/images/portfolio/item-2.png"
    url: "https://github.com/torih1541/House-Prices-Advanced-Regression-Techniques"

  - image: "assets/images/portfolio/item-3.png"
    url: "https://github.com/torih1541/Case-Study-1-DDS"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Model Building and Prediction", type: "model building" }
  - { title: "Machine Learning", type: "Machine learning" }
  - {title: "Exploratory Data Analysis", type: "Exploratory Data Analysis" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "https://github.com/hernandezv15/CaseStudy2DDS"
    portfolio-type:
      - type: "model building"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: hernandezv@smu.edu
